linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      # allow logrus only in lg package
      - github.com/sirupsen/logrus
  lll:
    line-length: 150
  nakedret:
    max-func-lines: 10

linters:
  enable:
    - golint
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - goimports
    - maligned
    - depguard
    - lll
    - nakedret
    - scopelint
    - gocritic

issues:
  exclude-use-default: false
  exclued:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

    # golint: False positive when tests are defined in package 'test'
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
